issues:
  comment: "This repository does not accept issues, as this is just a repository for my profile bio."

pulls:
  comment: "Pull requests are not accepted in this repository, as this is just a repository for my profile's bio."
